//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGen.exe
//   Version: 1.0.0
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Extension Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UAP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGen - Invoke the following command with a valid 
//   Introspection XML file:
//     AllJoynCodeGen -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace Callant {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement ICharacterLCDService. Instead, CharacterLCDServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class CharacterLCDServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] ICharacterLCDService
{
public:
    // Method Invocation Events
    event Windows::Foundation::TypedEventHandler<CharacterLCDServiceEventAdapter^, CharacterLCDSendCalledEventArgs^>^ SendCalled;

    // Property Read Events
    
    // Property Write Events

    // ICharacterLCDService Implementation
    virtual Windows::Foundation::IAsyncOperation<CharacterLCDSendResult^>^ SendAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ Platform::String^ interface_message);


};

} 
