//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGen.exe
//   Version: 1.0.0
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Extension Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UAP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGen - Invoke the following command with a valid 
//   Introspection XML file:
//     AllJoynCodeGen -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace Callant {

ref class CharacterLCDConsumer;

public ref class CharacterLCDSendResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    
    static CharacterLCDSendResult^ CreateSuccessResult()
    {
        auto result = ref new CharacterLCDSendResult();
        result->Status = Windows::Devices::AllJoyn::AllJoynStatus::Ok;
        return result;
    }
    
    static CharacterLCDSendResult^ CreateFailureResult(_In_ int32 status)
    {
        auto result = ref new CharacterLCDSendResult();
        result->Status = status;
        return result;
    }

private:
    int32 m_status;
};

public ref class CharacterLCDJoinSessionResult sealed
{
public:
    property int32 Status
    {
        int32 get() { return m_status; }
    internal:
        void set(_In_ int32 value) { m_status = value; }
    }

    property CharacterLCDConsumer^ Consumer
    {
        CharacterLCDConsumer^ get() { return m_consumer; }
    internal:
        void set(_In_ CharacterLCDConsumer^ value) { m_consumer = value; }
    };

private:
    int32 m_status;
    CharacterLCDConsumer^ m_consumer;
};

} 
